project:
  type: book
  output-dir: docs

book:
  title: "Django 2023"
  author: "Diego Saavedra"
  output-file: "curso_django_2023"  
  date: today
  date-format: medium
  favicon: python-logo.png
  description: El Curso Completo de Django te llevará desde los conceptos fundamentales hasta la creación práctica de un blog funcional. Con una combinación de teoría y proyectos prácticos, explorarás desde la configuración inicial hasta el despliegue en Azure. Diseñado tanto para principiantes como para aquellos que desean mejorar sus habilidades con Django, este curso ofrece una base sólida para la construcción de aplicaciones web robustas. ¡Embárcate en este emocionante viaje de aprendizaje en el mundo del desarrollo web con Django!
  keyword: Django, Desarrollo web, Python, Framework de desarrollo, Modelos y bases de datos, Vistas y plantillas, Autenticación y autorización, Docker, Despliegue en Azure, Git/GitHub, Programación web con Python, Creación de blogs con Django, Django Rest Framework, Contenedores, Sistema de control de versiones, Virtualización, Curso de desarrollo web, Proyecto educativo, Recurso gratuito, Contribuciones en GitHub.
  url: https://github.com/statick88/Course_of_python
  page-navigation: true
  sidebar: 
    logo: \images\django-img.png
    search: true
    collapse-level: 1

  repo-url: https://github.com/statick88/Course_of_python
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: python-logo.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Git y Github"
      chapters: 
        - unidades/unidad0/unidad0.qmd
    - part: "Introducción a Django"
      chapters: 
        - unidades/unidad1/unidad1.qmd
    - part: "Modelos y Bases de Datos"
      chapters: 
        - unidades/unidad2/unidad2.qmd
    - part: "Vistas y Plantillas"
      chapters: 
        - unidades/unidad3/unidad3.qmd
    - part: "Docker"
      chapters: 
        - unidades/unidad5/unidad5.qmd
bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Curso de Python 2023"
    group-position: 0
    creator: "Lcdo. Diego Saavedra Mgtr."
    rights: "© Statick | 2023"
    fig-responsive: true
    number-sections: true