project:
  type: book
  output-dir: docs

book:
  title: "Python 2023"
  author: "Diego Saavedra"
  output-file: "curso_python_2023"  
  date: today
  date-format: medium
  favicon: python-logo.png
  description: Este libro de Python te llevará desde los conceptos iniciales hasta la creación de aplicaciones prácticas con Frameworks como Django, Flask, Fast Api, PyScript y Regex. Apto para principiantes, aprenderás a programar y desarrollar proyectos reales con Bases de datos, APIs y más.
  keyword: Python, Programación, Fundamentos, Aplicaciones Prácticas, Instalación, Herramientas, API, Django Rest Framework, Bases de Datos, PostgreSQL, MongoDB, Control de Flujo, Funciones, Clases, Herencia, Módulos, Aprendizaje, Principiantes, Proyectos, Desarrollo Web, Django, Flask, Data Science, FastAPI, Práctica, Enseñanza, Gratis, Internet, Contribuir
  url: https://github.com/statick88/Course_of_python
  page-navigation: true
  sidebar: 
    logo: python-logo.png
    search: true
    collapse-level: 1

  repo-url: https://github.com/statick88/Course_of_python
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: python-logo.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Unidad 0: Git y Github"
      chapters: 
        - unidades/unidad0/unidad0.qmd
    - part: "Unidad 1: Introducción a Django"
      chapters: 
        - unidades/unidad1/unidad1.qmd
    - part: "Unidad 2: Introducción a Django"
      chapters: 
        - unidades/unidad2/unidad2.qmd
    - part: "Unidad 3: Vistas y Plantillas"
      chapters: 
        - unidades/unidad3/unidad3.qmd
    - part: "Unidad 5: Docker"
      chapters: 
        - unidades/unidad5/unidad5.qmd
bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Curso de Python 2023"
    group-position: 0
    creator: "Lcdo. Diego Saavedra Mgtr."
    rights: "© Statick | 2023"
    fig-responsive: true
    number-sections: true